### ISSUE TITLE
Lien vers dbCharts

### ISSUE THREAD

**Issue by skeggib** [domotique-s3/URLM#3]
Au lieu d'afficher uniquement les paramètres du lien quand on clique sur "Validate", on pourrai afficher le lien complet (et cliquable) sachant qu'on connait le lien vers dbCharts.

**Comment by drattak** [comment]
En fait l'idée c'était que l'on donnait uniquement le lien (ok pour donner le lien complet) et que celui-ci était copié dans le presse-papier pour pouvoir le coller dans un widget ou autre

**Comment by skeggib** [comment]
Donc le lien  complet non ?

Le ven. 4 mars 2016 15:19, Vincent Emile notifications@github.com a
écrit :

**Comment by drattak** [comment]
> "(ok pour donner le lien complet)"

:)
